production: false

authentication:
  image:
    pullPolicy: IfNotPresent
    version: latest
    repository: glog/authentication
  mongodb:
    host: glog-mongodb-headless
    port: 27017
  environment:
    secret: verysecret
    token:
      expire: 3600

mongodb:
  architecture: replicaset
  auth:
    enabled: false
