apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-authentication
spec:
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      volumes:
      - name: environment
        configMap:
          name: authentication-environment
          items:
          - key: .env
            path: .env
      containers:
      - name: authentication
        imagePullPolicy: {{ .Values.authentication.image.pullPolicy }}
        image: {{ .Values.authentication.image.repository }}:{{ .Values.authentication.image.version }}
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
        env:
          - name: MONGO_URI
            valueFrom: 
              secretKeyRef: 
                name: {{ .Release.Name }}-mongo-uri
                key: uri
        volumeMounts:
        - name: environment
          mountPath: /home/app/.env
          subPath: .env
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 2
          failureThreshold: 1
          

